"""PM Cockpit core — pure domain types (C1). Re-exports the public API."""

from core.paths import (
    ALLOWED_BUCKETS,
    DATE_RE,
    FILENAME_RE,
    MAX_STEM_LEN,
    PROJECT_CODE_RE,
    SLUG_RE,
    STEM_RE,
    normalize_relpath,
    slugify,
)
from core.values import ALLOWED_REF_TABLES, EventRef, Owner, PreparedFor
from core.enums import (
    ALLOWED_ACTION_TRANSITIONS,
    ActionStatus,
    EventKind,
    GateOutcome,
    ProjectStatus,
    SignalKind,
    SourceType,
)
from core.errors import (
    CoreError,
    CycleCloseError,
    DataError,
    EvidenceConflict,
    GateMissing,
    IntegrityError,
    InvalidSlug,
    MissingFileError,
    OwnerError,
    PathEscape,
    PdfError,
    ServiceError,
    UnknownProjectData,
    UnknownProjectService,
)
from core.time import now_utc
from core.hash import A4_PAGE_PT, SHORT_ID_LEN, sha256_bytes, sha256_file, short_id

__all__ = [
    "ALLOWED_BUCKETS",
    "DATE_RE",
    "FILENAME_RE",
    "MAX_STEM_LEN",
    "PROJECT_CODE_RE",
    "SLUG_RE",
    "STEM_RE",
    "normalize_relpath",
    "slugify",
    "ALLOWED_REF_TABLES",
    "EventRef",
    "Owner",
    "PreparedFor",
    "ALLOWED_ACTION_TRANSITIONS",
    "ActionStatus",
    "EventKind",
    "GateOutcome",
    "ProjectStatus",
    "SignalKind",
    "SourceType",
    "CoreError",
    "CycleCloseError",
    "DataError",
    "EvidenceConflict",
    "GateMissing",
    "IntegrityError",
    "InvalidSlug",
    "MissingFileError",
    "OwnerError",
    "PathEscape",
    "PdfError",
    "ServiceError",
    "UnknownProjectData",
    "UnknownProjectService",
    "now_utc",
    "A4_PAGE_PT",
    "SHORT_ID_LEN",
    "sha256_bytes",
    "sha256_file",
    "short_id",
]
