#!/usr/bin/env python3
"""Generate the Context Pack signature sheet (MOSAIC section 6).

A signature sheet must answer every question a card can ask about another
layer WITHOUT opening its source. That means three things, not one:

    functions   - full parameter list, defaults, return annotation
    classes     - dataclass fields with types and defaults, plus methods
    enums       - every member and its value

Two incomplete sheets caused four failed build sessions on this project:
a grep-based sheet truncated every wrapped signature, and an AST sheet
that emitted class names but not dataclass fields. Both looked complete.
Hence --check, and hence the self-test below.

Usage:
    python tools/sigsheet.py                 write core.sig.txt
    python tools/sigsheet.py --check         exit 1 if the file is stale
    python tools/sigsheet.py --selftest      prove the generator is complete
    python tools/sigsheet.py --out FILE      write somewhere else

Add to the gate:
    python tools/sigsheet.py --check
"""

from __future__ import annotations

import argparse
import ast
import pathlib
import sys
import tempfile

# Layers scanned, in dependency order. Add a layer here when it is created.
LAYERS = ["core", "data", "services", "api", "app"]

OUTFILE = "core.sig.txt"

HEADER = [
    "# Signature sheet - generated by tools/sigsheet.py. Do not hand-edit.",
    "# Functions carry full parameter lists. Classes carry their fields.",
    "# Enums carry their members. This file is the ONLY signature source a",
    "# card needs; if something is missing from it, the sheet is wrong -",
    "# say so rather than opening the source.",
    "",
]


def _ann(node) -> str:
    return ast.unparse(node) if node is not None else ""


def _fn(node, indent: str = "") -> str:
    ret = f" -> {_ann(node.returns)}" if node.returns else ""
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    return f"{indent}{prefix} {node.name}({ast.unparse(node.args)}){ret}"


def _is_enum(node: ast.ClassDef) -> bool:
    for b in node.bases:
        if "Enum" in ast.unparse(b):
            return True
    return False


def _class(node: ast.ClassDef, path: pathlib.Path) -> list[str]:
    bases = ", ".join(ast.unparse(b) for b in node.bases)
    head = f"{path}:{node.lineno}: class {node.name}"
    if bases:
        head += f"({bases})"
    lines = [head]
    enum = _is_enum(node)

    for m in node.body:
        # annotated field:  name: str = "x"
        if isinstance(m, ast.AnnAssign) and isinstance(m.target, ast.Name):
            default = f" = {ast.unparse(m.value)}" if m.value else ""
            lines.append(f"    {m.target.id}: {_ann(m.annotation)}{default}")
        # bare assignment: enum members, class constants
        elif isinstance(m, ast.Assign):
            for tg in m.targets:
                if isinstance(tg, ast.Name) and not tg.id.startswith("_"):
                    tag = "  # enum member" if enum else ""
                    lines.append(f"    {tg.id} = {ast.unparse(m.value)}{tag}")
        elif isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if m.name.startswith("_") and m.name != "__init__":
                continue
            lines.append(_fn(m, indent="    "))
    return lines


def generate(root: pathlib.Path, layers: list[str]) -> str:
    out: list[str] = list(HEADER)
    for layer in layers:
        d = root / layer
        if not d.is_dir():
            continue
        files = sorted(p for p in d.rglob("*.py") if "__pycache__" not in p.parts)
        if not files:
            continue
        out.append(f"# ---- {layer}/ ----")
        for f in files:
            rel = f.relative_to(root)
            try:
                tree = ast.parse(f.read_text(encoding="utf-8"))
            except SyntaxError as exc:
                out.append(f"{rel}: !! SYNTAX ERROR line {exc.lineno} - sheet incomplete")
                continue
            for n in tree.body:
                if isinstance(n, ast.ClassDef):
                    out.extend(_class(n, rel))
                elif isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if n.name.startswith("_"):
                        continue
                    out.append(f"{rel}:{n.lineno}: {_fn(n)}")
                elif isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name):
                    if not n.target.id.startswith("_"):
                        default = f" = {ast.unparse(n.value)}" if n.value else ""
                        out.append(f"{rel}:{n.lineno}: {n.target.id}: "
                                   f"{_ann(n.annotation)}{default}")
                elif isinstance(n, ast.Assign):
                    for tg in n.targets:
                        if isinstance(tg, ast.Name) and tg.id.isupper():
                            out.append(f"{rel}:{n.lineno}: {tg.id} = "
                                       f"{ast.unparse(n.value)}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def selftest() -> int:
    """Prove the generator emits all three kinds. Both past failures would
    have been caught here."""
    src = '''
from dataclasses import dataclass
from enum import Enum

MAX_ROWS = 40

class Status(str, Enum):
    OPEN = "open"
    DONE = "done"

@dataclass(frozen=True)
class Row:
    code: str
    name: str | None = None

class Repo:
    def create(
        self,
        code: str,
        *,
        title: str = "",
        limit: int | None = None,
    ) -> Row: ...

def helper(a: int, b: str = "x") -> bool: ...
'''
    with tempfile.TemporaryDirectory() as td:
        root = pathlib.Path(td)
        (root / "core").mkdir()
        (root / "core" / "m.py").write_text(src, encoding="utf-8")
        sheet = generate(root, ["core"])

    checks = {
        "wrapped signature keeps its parameters":
            "def create(self, code: str, *, title: str='', limit: int | None=None) -> Row" in sheet,
        "dataclass fields are listed":
            "code: str" in sheet and "name: str | None = None" in sheet,
        "enum members are listed":
            "OPEN = 'open'" in sheet and "DONE = 'done'" in sheet,
        "module constants are listed":
            "MAX_ROWS = 40" in sheet,
        "module functions are listed":
            "def helper(a: int, b: str='x') -> bool" in sheet,
        "class bases are shown":
            "class Status(str, Enum)" in sheet,
        "no entry is truncated at an open paren":
            not any(l.rstrip().endswith("(") for l in sheet.splitlines()),
    }
    ok = True
    for label, passed in checks.items():
        print(f"  {'PASS' if passed else 'FAIL'}  {label}")
        ok = ok and passed
    if not ok:
        print("\nself-test FAILED - the generator is incomplete", file=sys.stderr)
        print(sheet, file=sys.stderr)
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed sheet is stale")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--out", default=OUTFILE)
    ap.add_argument("--root", default=".")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    root = pathlib.Path(args.root).resolve()
    sheet = generate(root, LAYERS)
    target = root / args.out

    if args.check:
        if not target.exists():
            print(f"{args.out} is missing - run: python tools/sigsheet.py",
                  file=sys.stderr)
            return 1
        if target.read_text(encoding="utf-8") != sheet:
            print(f"{args.out} is STALE - run: python tools/sigsheet.py",
                  file=sys.stderr)
            return 1
        print(f"{args.out} is current ({len(sheet.splitlines())} lines)")
        return 0

    target.write_text(sheet, encoding="utf-8")
    print(f"wrote {args.out} ({len(sheet.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
